# Generated by Django 3.2.25 on 2024-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_sizevariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizevariant',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='size_variants',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.SizeVariant'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
