# Generated by Django 3.2.25 on 2024-09-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20240925_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size_variants',
            field=models.ManyToManyField(related_name='products', to='product.SizeVariant'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
