# Generated by Django 3.2.25 on 2024-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20240927_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
