# Generated by Django 3.2.25 on 2024-10-18 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraloffer',
            name='referred_user',
        ),
        migrations.AddField(
            model_name='referraloffer',
            name='referrer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
            preserve_default=False,
        ),
    ]
