# Generated by Django 3.2.25 on 2024-10-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20241009_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Razorpay', 'Razorpay'), ('Cash on Delivery', 'Cash on Delivery')], max_length=20),
        ),
    ]
