# Generated by Django 3.2.25 on 2024-10-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20241016_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='credited_to_wallet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_canceled',
        ),
    ]
